### ISSUE TITLE
The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by noammaoz** [flagbug/YoutubeExtractor#131]
Hi,

I'm working with the latest version and some of YouTube videos URL throw exception of "The remote server returned an error: (403) Forbidden."

For example:
https://www.youtube.com/watch?v=g_2X59Cycrc working fine without any exception
https://www.youtube.com/watch?v=jKbR7u8J5PU throw exception in VideoDownloader.cs

using (WebResponse response = request.GetResponse()) 

Can you please help with this issue?

Thanks,

**Comment by Zyano** [comment]
Hey there

The issues is related to the way signature decryption is done a solution to the issue have been posted in this issues from a couple of days ago

https://github.com/flagbug/YoutubeExtractor/issues/129

The work around was posted by @tariqalkhassa

 remember to search :)

**Comment by Lesslie123** [comment]
I've did the above step at it doesn't work. I think too that it has something to do how the signature is put into the dictionary.

**Comment by flagbug** [comment]
Should be fixed with https://github.com/flagbug/YoutubeExtractor/pull/151

**Comment by Taki7o7** [comment]
i've the same problem now for some videos

But i am using an if

```
if (video.RequiresDecryption)
                    {
                        DownloadUrlResolver.DecryptDownloadUrl(video); 
                    }
```

**Comment by ghost** [comment]
I tried to use what you. But unfortunately it did not help .. I still have a 403 error.. this problem I have in audio/video

**Comment by MaxtorCoder** [comment]
I have the same issue, with downloading a video.
