### ISSUE TITLE
cannot add package to iOS

### ISSUE THREAD

**Issue by RogerSchmidlin** [flagbug/YoutubeExtractor#166]
What do I do wrong? I am trying to add the package in Xamarin in iOS. It worked like a charm in Android. Can you give me some advice?

"Could not install package 'YoutubeExtractor 0.10.8'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework"

**Comment by flagbug** [comment]
I've just pushed version 0.10.9 to NuGet, can you try it out?

**Comment by RogerSchmidlin** [comment]
Happy New Year!
Yes, it worked :+1:  Thanks for that. I still get the problem with certain videos taking too long to retrieve the path and problem playing the video with MediaPlayer. I posted that in the other thread.
Thanks for doing this great module and for the prompt response

**Comment by flagbug** [comment]
Cool, I'll close this and we track the other error in the other issue!
