### ISSUE TITLE
Forbidden (409)

### ISSUE THREAD

**Issue by mysteryx93** [flagbug/YoutubeExtractor#226]
Since recently, I started receiving Forbidden (409) error on downloads. If I download your original package and run ExampleApplication, it returns Forbidden.

**Comment by SomeOneMore** [comment]
Same behaviour Error 403. Forbidden.

**Comment by jphellemons** [comment]
Same here...  I got it on VideoDownloader when calling .Execute()

**Comment by hakiour** [comment]
Same on VideoLibrary, I think Youtube change something

**Comment by SomeOneMore** [comment]
This issue is solved ;-)
https://github.com/flagbug/YoutubeExtractor/issues/228 #228

**Comment by jphellemons** [comment]
@SomeOneMore it is (just verified it) but there is no pull request for it? or am I missing something? :shipit:  👍

**Comment by Tinguely** [comment]
I am still getting this issue, all the videos are flagged as not false for the CanExtractAudio leading to an access denied when running Execute

**Comment by jphellemons** [comment]
@Tinguely are you using the nuget? Or latest source? Because the PR was accepted about 2 days ago.

**Comment by mysteryx93** [comment]
As a side note, YoutubeExtractor doesn't support many YouTube formats including 256kb AAC, Vorbis, Opus and 60fps videos. Some of these formats require parsing additional data. I submitted a pull request hoping to not have to maintain my own branch anymore, because it is getting cumbersome to merge all other updates. In the meantime, you can get these extra features in my branch
https://github.com/mysteryx93/YoutubeExtractor

**Comment by Tinguely** [comment]
@jphellemons Thank you, I was tired, didn't even think of that!

**Comment by Tinguely** [comment]
Hmm, just got off work and tried to the latest code, still not able to find any videos it can extract. I am essentially just using the example code.

**Comment by markwalsh-liverpool** [comment]
#237 Should be implemented to fix this
